name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  # Cache versioning
  CACHE_VERSION: v2
  # Cypress cache
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
  # PNPM settings
  PNPM_VERSION: 10
  # CI specific settings
  CI: true
  NODE_ENV: test

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ env.CACHE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ env.CACHE_VERSION }}-
          
    - name: Setup Cypress cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CYPRESS_CACHE_FOLDER }}
        key: ${{ runner.os }}-cypress-${{ env.CACHE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-cypress-${{ env.CACHE_VERSION }}-
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      
    - name: Install Cypress binary
      run: pnpm cypress install
      
    - name: Verify Cypress installation
      run: pnpm cypress verify
      
    - name: Cache build output
      uses: actions/cache@v4
      with:
        path: dist
        key: ${{ runner.os }}-build-${{ env.CACHE_VERSION }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.CACHE_VERSION }}-
        
    - name: Run E2E tests
      run: pnpm test:e2e:ci
      env:
        CYPRESS_baseUrl: http://localhost:4173
        CI: true
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-results-node-${{ matrix.node-version }}-${{ github.run_id }}
        path: |
          cypress/results
          cypress/reports
        retention-days: 7

